spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/workspaces/h2_db_files/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # 로컬환경에서만 해야 한다. -> 이미 table이 있으면,  drop하고 새로 생성해버린다.
    properties:
      hibernate:
        format_sql: true
logging.level:
  org.hibernate.SQL: debug